function [] = FileCleanup_v6_0(OutputPathName)
%% FileCleanup is a quick way to clean up the data generated by one experimental runs
% Updated on 4/29/2018 by Waddah Moghram
%% Files that will be deleted are:
    % disp%04.dat, tmpNodes%04.dat, pathTrackedDisp.dat, pathTrackedSubDisp2,
    % output.dat
    % GUIelements.dat, GUIelements_out.dat, GUInodes.dat, GUInodes_out.dat, 
    % roughDisp.dat, 
    % smoothedDispFinex.dat, smoothedDispFiney.dat,
    % Tip_Coordinates.dat, Bead_Coordinates.dat
    % capsP%04.dat, 
    % Tip Coordinates.txt, Clean Compiled Data.txt, dTime.txt, 
    % CleanCompiledData.dat
%% Written by Waddah Moghram, PhD Student in Biomedical Engineering, on 1/22/2018-1/24/2018.
% Updated on 1/30/2018 to replace try...end structure with [status,msg] = mkdir() or movefile()
% Updated on 5/15/2019 to add an option to choose the folder that needs to be cleaned up

if isempty(OutputPathName)
    OutputPathName = uigetdir('Open the directory that contains the output files to be cleaned up');
end



%% 1. Create a directory to dump all the files generated in them.
    [status,msg] = mkdir('tracking_output');
    %     hEditor = matlab.desktop.editor.getActive;
    %     
    %     %Close all files.
    %     while ~isempty(hEditor);
    %       closeNoPrompt(hEditor);
    %       hEditor = matlab.desktop.editor.getActive;
    %     end
    fclose('all');               
    
 %% 2. Moving files into the created directory

    % 'Tip_Coordinates.dat' & 'Tip_Coordinates_Info.dat'
    [status, msg] = movefile(fullfile(OutputPathName,'Tip_Coordinates*'), fullfile(OutputPathName,'Tip_Coordinates'));
 
     % Move all the TipP****.tif. Added on 2/1/2018
    [status, msg] = movefile(fullfile(OutputPathName,'Tip*'), fullfile(OutputPathName,'Tip_Images'));                
    
     % Bead_Coordinates.dat' & 'Bead_Coordinates_Info.dat'
    [status, msg] = movefile(fullfile(OutputPathName,'Bead_Coordinates*'), fullfile(OutputPathName,'Bead_Coordinates'));
    
    % Move all the capsP****.tif
    [status, msg] = movefile(fullfile(OutputPathName,'caps*'), fullfile(OutputPathName,'Bead_Images'));
    
    % Move the TimeStamps extracted from the ND2 File
    [status, msg] = movefile(fullfile(OutputPathName,'*dTime*'), fullfile(OutputPathName,'Time_Stamps'));
    
    % 'Clean_Compiled_Data.dat' and 'Clean_Compiled_Data_Info.dat'
    [status, msg] = movefile(fullfile(OutputPathName,'Clean_Compiled_Data*'), fullfile(OutputPathName,'Compiled_Output'));
     
    % Move output from rrImageTrackGUI
    [status, msg] = movefile( fullfile(OutputPathName,'disp*'), fullfile(OutputPathName, 'Bead_Tracking'));
    [status, msg] = movefile( fullfile(OutputPathName,'tmpNodes*'), fullfile(OutputPathName,'Bead_Tracking'));
    [status, msg] = movefile( fullfile(OutputPathName,'pathTracked*'), fullfile(OutputPathName,'Bead_Tracking'));
    [status, msg] = movefile( fullfile(OutputPathName,'smoothedDisp*'), fullfile(OutputPathName,'Bead_Tracking'));
    [status, msg] = movefile( fullfile(OutputPathName,'roughDisp*'), fullfile(OutputPathName,'Bead_Tracking'));
    [status, msg] = movefile(fullfile(OutputPathName,'GUIelements*'), fullfile(OutputPathName,'Bead_Tracking'));          % GUIelements.dat and GUIelements_out.dat
    [status, msg] = movefile(fullfile(OutputPathName,'GUInodes*') ,fullfile(OutputPathName,'Bead_Tracking'));             % GUInodes.dat and GUInodes_out.dat
    [status, msg] = movefile(fullfile(OutputPathName,'Tracking_Param**') ,fullfile(OutputPathName,'Bead_Tracking'));             % GUInodes.dat and GUInodes_out.dat     %Added on 5/8/2018
    
    [status, msg] = copyfile(fullfile(OutputPathName,'output*'), fullfile(OutputPathName,'Bead_Tracking'));               %sometimes output.dat stays output if tracking is not complete
    [status, msg] = movefile(fullfile(OutputPathName,'output*'), fullfile(OutputPathName,'Bead_Tracking'));
   end
