% Written by Waddah Moghram on 2/7/2019 
% This script identifies the bead that has displaced the most (beadID)
% It also identifes how much that displacement was and at what frame
% You can use this for any field generated by TFM package (e.g., displacement field, force field, etc.)
% v1.00


    NumFrames = numel(displField);
    FrameNumber = 0;
    MaxDisplFieldIndex = 0;
    FrameSeq = 1:NumFrames;
    % % # of cycles
    % cycles = 7;

    % displFieldNetMaxPointInFrame = 0;
    displFieldNetMaxPointInFrame = zeros(numel(FrameSeq),1);
    tmpMaxDisplFieldNetInFrame = 0;
    tmpMaxDisplFieldInFrameIndex = 0;

    try 
        FrameRate = 1/MD.timeInterval_;
    catch
        FrameRate = 1/ 0.025;           % (40 frames per seconds)              
    end
    prompt = {sprintf('Choose the Frame Rate per second for this movie. [Default, %.4f]', FrameRate)};
    dlgTitle =  'Frames Per Second';
    FrameRateStr = inputdlg(prompt, dlgTitle, [1, 90], {num2str(FrameRate)});
    if isempty(FrameRateStr), return; end
    FrameRate = str2double(FrameRateStr{1});                                  % Convert to a number
    TimeFramesSec = FrameSeq * FrameRate;       
    

    try 
    	LastFrame = sum(arrayfun(@(x) ~isempty(x.vec), displField));
    catch
        LastFrame = size(displField,2);
    end


%% Finding maximum bead

for ii = FrameSeq
    NetdisplFieldAllPointsInFrame = vecnorm(displField(ii).vec,2,2);
    [tmpMaxDisplFieldNetInFrame, tmpMaxDisplFieldInFrameIndex] =  max(NetdisplFieldAllPointsInFrame);          % maximum item in a column
    
    if tmpMaxDisplFieldNetInFrame > displFieldNetMaxPointInFrame
        displFieldNetMaxPointInFrame(ii) = tmpMaxDisplFieldNetInFrame;
        displFieldMaxPosFrame = displField(ii).pos; 
        displFieldMaxVecFrame = displField(ii).vec;
        MaxDisplFieldIndex = tmpMaxDisplFieldInFrameIndex;
        FrameNumber = ii;
    end 
end
fprintf('Maximum Net Displacement = %g pixels at ', displFieldNetMaxPointInFrame(FrameNumber));
fprintf('[x,y] = [%g, %g] pixels. \n\t in Frame #%d, Point Index #%d \n', displFieldMaxPosFrame(MaxDisplFieldIndex, 1), displFieldMaxPosFrame(MaxDisplFieldIndex, 2), FrameNumber, MaxDisplFieldIndex)
fprintf('Maximum displacement [disp_x, disp_h] =  [%f, %f] pixels or net displacement [disp_net] = [%f] pixels. \n',  displFieldMaxVecFrame(MaxDisplFieldIndex, 1), displFieldMaxVecFrame(MaxDisplFieldIndex, 2) , displFieldNetMaxPointInFrame(FrameNumber))

%%     
    BeadDisplPixels = [];
    for ii = FrameSeq
        BeadDisplPixels = vertcat(BeadDisplPixels,  displField(ii).vec(MaxDisplFieldIndex,:));
    end 
    
    try 
        BeadDisplMicrons = BeadDisplPixels * (MD.pixelSize_ / 1000);
    catch
        BeadDisplMicrons = AllFrames *   0.215032122665759;     % (30X Objective Lens)        
    end
    
      
    %% ---------------- PLOTS
    % From field vectors are not cumulative.
    resultant_vecPixels = vecnorm(BeadDisplPixels,2,2);
    resultant_vecMicron = vecnorm(BeadDisplMicrons,2,2);
    
    figHandle2 = figure('color','w');
    
    xlabel('Time, (s)');
    ylabel('Maximum bead displacement, \Delta(t)_{TFM, max} (\mum)')
    xlim( [TimeFramesSec(1), TimeFramesSec(end)]);
    title('Maximum Bead Displacement under epifluorescent mode')
    set(gca,'FontWeight','bold')
    hold on
    plot(TimeFramesSec, resultant_vecMicron(:,:), 'r.-', 'MarkerSize', 1) 

    outputPlotFileNameFig = fullfile(AnalysisOutputPath, 'Delta TFM max.fig');
    outputPlotFileNameTIF = fullfile(AnalysisOutputPath, 'Delta TFM max.tif');
    
    MaxDisplacementDetails.TimeFrameSeconds = TimeFramesSec;
    MaxDisplacementDetails.MaxBeadNetDisplacementMicron = resultant_vecMicron;

    hgsave(figHandle2, outputPlotFileNameFig,'-v7.3'); 
    FrameImage = getframe(figHandle2);       
    imwrite(FrameImage.cdata, outputPlotFileNameTIF);
    
    
