function [MaxVectorr, XYcoordiantes, FrameNumber, MaxDisplFieldIndex) = MaxVectorOverTime(vectorField)
    % Written by Waddah Moghram on 2/7/2019 
    % This script identifies the bead that has displaced the most (beadID)
    % It also identifes how much that displacement was and at what frame
    % You can use this for any field generated by TFM package (e.g., displacement field, force field, etc.)
    % v1.00

    NumFrames = numel(displField);
    FrameNumber = 0;
    MaxDisplFieldIndex = 0;
    % displFieldNetMaxPointInFrame = 0;
    displFieldNetMaxPointInFrame = zeros(numel(FrameSeq),1);
    tmpMaxDisplFieldNetInFrame = 0;
    tmpMaxDisplFieldInFrameIndex = 0;


    FrameSeq = 1:NumFrames;
    % % # of cycles
    % cycles = 7;

    for ii = FrameSeq
        NetdisplFieldAllPointsInFrame = vecnorm(displField(ii).vec,2,2);
        [tmpMaxDisplFieldNetInFrame,tmpMaxDisplFieldInFrameIndex] =  max(NetdisplFieldAllPointsInFrame);          % maximum item in a column

        if tmpMaxDisplFieldNetInFrame > displFieldNetMaxPointInFrame
            displFieldNetMaxPointInFrame(ii) = tmpMaxDisplFieldNetInFrame;
            displFieldMaxPosFrame = displField(ii).pos; 
            displFieldMaxVecFrame = displField(ii).vec;
            MaxDisplFieldIndex = tmpMaxDisplFieldInFrameIndex;
            FrameNumber = ii;
        end 
    end
    fprintf('Maximm Net Displacement = %g pixels at ', displFieldNetMaxPointInFrame(FrameNumber));
    fprintf('[x,y] = [%g, %g] pixels. \n\t in Frame #%d, Point Index #%d \n', displFieldMaxPosFrame(MaxDisplFieldIndex, 1), displFieldMaxPosFrame(MaxDisplFieldIndex, 2), FrameNumber, MaxDisplFieldIndex)
    % fprintf('Maximum displacement [disp_x, disp_h] =  [%f, %f] pixels or net displacement [disp_net] = [%f] pixels. \n',  displFieldMaxVecFrame(MaxDisplFieldIndex, 1), displFieldMaxVecFrame(MaxDisplFieldIndex, 2) , displFieldNet)')

end