function [HeaderData, HeaderTitle] = ReadSensorDataFileHeaderOnly(SensorDataFullFileName)
%% v7.20. Updated by Waddah Moghram on 2019-06-03
% NOTE: Sensor dats is the raw 
%{
    v7.00 updated by Waddah Moghram on 2019-05-25
        1. Fixed Extra Zero point at the end
        2. Added the possibility of plotting the data to check if everything is OK

    v6.00 Updated on 2018-04-28 to reflected updated header files.
    This file will extract the output of the latest files generated by LabVIEW Flux Experiments. 
    Based on old ReadLabVICode.m of 11/1/2017, and ReadSensorDataFile_v_1_0.m
    Fixed glitch that skipped the first datapoint by changing the starting row for dlmread(). 

    Written by Waddah Moghram, PhD Candidate in Biomedical Engineering at the University of Iowa, on 1/18/2018. Updated on 4/28/2018 to reflected updated header files.

    Intput are SensorDataFile that user-input after this program is run, and the number of header lines
    Check the outline of the header below.
    Optional filename for sensor file

    Output are the SensorData, HeaderData & HeaderTitle. (For the v8.0 and later)
    HeaderData are Rows 2,4,6,8, 10 and 12
    HeaderTitle are Rows 1,3,5,7, 9 and 11
    SensorData are Rows 11 and thereafter
    Row 12 is the header for the SensorData
    
    %% Older Versions:
    ReadSensorDataFile_v_4_0
    HeaderData are Rows 2,4,6,8 and 10
    HeaderTitle are Rows 1,3,5,7 and 9
    SensorData are Rows 11 and thereafter
    Row 10 is the header for the SensorData
    
    ReadSensorDataFile_v_1_0 This file will extract the output of the latest
    files generated by LabVIEW Flux Experiments. Based on old ReadLabVICode.m
    of 11/1/2017. SensorDataFile is user-selected after this program is run.
    Returns the SensorData, HeaderData & HeaderTitle. 
    HeaderData are Rows 2,4,6, and 8
    HeaderTitle are Rows 1,3,5, and 7
    Sensor Data are Rows 9 and thereafter
    Programmed by Waddah Moghram, PhD Candindate in Biomedical Engineering on
     10/4/2017

    %% Outline of the header and data points of the file generated by LabVIEW. Note: they are "Tab-Delimited"
    
    
    v15.00 (8 header lines or 12 rows). Example Below
        Magnetic Sensor Zero (V)	Magnetic Sensor Sensitivity (V/Gs)	Number of Cycles	Sampling Rate (Samples/Sec)
        2.467116	0.0029794	3	30000
        ON Proportional Gain (K_c)	 Integral Time (T_i, min)	Derivative Time (T_d, min)	Samples pushed to PID
        1.800000	3.500000E-6	0.000000E+0	30
        OFF Proportional Gain (K_c)	Integral Time (T_i, min)	Derivative Time (T_d, min)	Needle Used
        0.300000	3.500000E-6	0.000000E+0	1
        Flux ON Relative Setpoint (Gs)	Null Flux - Observed (Gs)	Pre-Zero Interval (s)	Post-Zero Interval (s)
        -175.000000	3.000000	2.000000	0.000000
        Temperature (ºC)	Needle Inclination Angle (º)	Magnetic Beads Diameter (Micron)	Relative Humidity
        25.7	20	4.5	0.42
        Null Flux Corrected (Gs)	Magnetic Bead Z-Level (Micron)	Fluoro Beads Z-Level (Micron)	Tip Z-Level (Micron)
        12.092087	4627.00	4623.00	4637.00
        Gel Measured Thickness (Micron)	Initial Separation Distance (Micron)	Image Scale (Micron/pixel)	Fluoro Beads Diameter (Micron)
        650.00	17.00	0.21500	0.5
        Ramp Steps	Total Ramp Time (ms)	===============	===============
        7	490	0.0	0.0 
    
    --------------------------
    v11.00 (6 header lines or 12 rows)
    
    --------------------------
    v10.00 (6 header lines or 12 rows)  
    
    
    --------------------------
    v9.70 (5 header lines or 10 rows)  
    
    
    --------------------------
    v9.60 (5 header lines or 10 rows)  
    
    
    --------------------------
    v9.50 (5 header lines or 10 rows)  
    
    
    --------------------------
    v8.0 - 9.40 (5 header lines or 10 rows)
        Row 0:
           Magnetic Sensor Zero (V)	Magnetic Sensor Sensitivity (V/Gs)	Number of Cycles	Sampling Rate (Samples/Sec)
        Row 1:
          The Corresponding Values for the headers above
        Row 2: 
          ON Proportional Gain (K_c)	 Integral Time (T_i, min)	Derivative Time (T_d, min)	Samples pushed to PID
        Row 3:    
          The corresponding values for the headers above.
        Row 4: 
          OFF Proportional Gain (K_c)     Integral Time (T_i, min)	Derivative Time (T_d, min)      Needle Used
        Row 5:    
          The Corresponding values for the headers above.
        Row 6:
          Flux ON Relative Setpoint (Gs)      Flux Observed Zero (Gs)     Pre- Zero Interval (s)      Post- Zero Interval (s)
        Row 7:
          The Corresponding values for the headers above.
        Row 8:
          Temperature (ºC)	Needle Inclination Angle (º)	Magnetic Beads Diameter (Micron)	Relative Humidity
        Row 9:
          The Corresponding values for the headers above.
        Row 10:
          Index       Flux Sensor (V)     Current Sensor (V or A) 	Camera Exposure TTL (V)     
        Row 11 until EOF:
        The Corresponding values for the headers above.  
    --------------------------
    v8.0 - 9.40 (5 header lines or 10 rows)
        Row 0:
           Magnetic Sensor Zero (V)	Magnetic Sensor Sensitivity (V/Gs)	Number of Cycles	Sampling Rate (Samples/Sec)
        Row 1:
          The Corresponding Values for the headers above
        Row 2: 
          ON Proportional Gain (K_c)	 Integral Time (T_i, min)	Derivative Time (T_d, min)	Samples pushed to PID
        Row 3:    
          The corresponding values for the headers above.
        Row 4: 
          OFF Proportional Gain (K_c)     Integral Time (T_i, min)	Derivative Time (T_d, min)      Needle Used
        Row 5:    
          The Corresponding values for the headers above.
        Row 6:
          Flux ON Relative Setpoint (Gs)      Flux Observed Zero (Gs)     Pre- Zero Interval (s)      Post- Zero Interval (s)
        Row 7:
          The Corresponding values for the headers above.
        Row 8:
          Temperature (ºC)	Needle Inclination Angle (º)	Magnetic Beads Diameter (Micron)	Relative Humidity
        Row 9:
          The Corresponding values for the headers above.
        Row 10:
          Index       Flux Sensor (V)     Current Sensor (V or A) 	Camera Exposure TTL (V)     
        Row 11 until EOF:
        The Corresponding values for the headers above.  
    
    --------------------------
    v7.0 - 7.4 (4 header lines or 8 rows)
        Row 0:
           Magnetic Sensor Zero (V)	Magnetic Sensor Sensitivity (V/GS)      Number of Cycles        Step Duration (Samples/Sec)
        Row 1:
          The Corresponding Values for the headers above
        Row 2: 
          Proportional Gain (K_c)     Integral Time (T_i, min)        Derivative Time (T_d, min)  	Samples pushed to PID
        Row 3:    
          The corresponding values for the headers above.
        Row 4: 
          Flux ON Relative Setpoint (GS)  	Flux Observed Zero (GS)     Pre- Zero Interval (s)      Post- Zero Interval (s)
        Row 5:    
          The Corresponding values for the headers above.
        Row 6:
          Temperature (ºC)        Needle Inclination Angle (º)        Magnetic Beads Diameter (Micron)        Relative Humidity
        Row 7:
          The Corresponding values for the headers above.
        Row 8:
          Index           Flux Sensor (V)         Current Sensor (V or A)             Camera Exposure TTL (V)
        Row 9 until EOF:
        The Corresponding values for the headers above.

    --------------------------
    v6.0 and v5.20     (4 header lines or 8 rows)
        Row 0:
           Magnetic Sensor Zero (V)	Magnetic Sensor Sensitivity (V/GS)  	Number of Cycles	Step Duration (Samples/Sec)
        Row 1:
          The Corresponding Values for the headers above
        Row 2: 
          Proportional Gain (K_c)	    Integral Time (T_i, min)	 Derivative Time (T_d, min)  	Samples pushed to PID
        Row 3:
          The corresponding values for the headers above.
        Row 4: 
          Flux ON Relative Setpoint (GS)	 Flux Observed Zero (GS)	Pre- Zero Interval (s)	Post- Zero Interval (s)
        Row 5:    
          The Corresponding values for the headers above.
        Row 6:
          Solution Temperature (ºC)	Needle Inclination Angle (º)	Magnetic Beads Diameter (micron)	===============    
        Row 7:
          The Corresponding values for the headers above.
        Row 8:
        Index     Flux Sensor (V)     Current Sensor (V or A)     Camera Exposure TTL (V)
        Row 9 until EOF:
        The Corresponding values for the headers above.
    
    --------------------------
    v5.00  (3 header lines or 6 rows):
        Row 0:
           Magnetic Sensor Zero (V)	Magnetic Sensor Sensitivity (V/GS)  	Number of Cycles	Step Duration (Samples/Sec)
        Row 1:
          The Corresponding Values for the headers above
        Row 2: 
          Proportional Gain (K_c)	    Integral Time (T_i, min)	 Derivative Time (T_d, min)  	Samples pushed to PID
        Row 3:
          The corresponding values for the headers above.
        Row 4: 
          Flux ON Relative Setpoint (GS)	 Flux Observed Zero (GS)	Pre- Zero Interval (s)	Post- Zero Interval (s)
        Row 5:    
          The Corresponding values for the headers above.
        Row 6:
        Index     Flux Sensor (V)     Current Sensor (V or A)     Camera Exposure TTL (V)
        Row 7 until EOF:
        The Corresponding values for the headers above.
    
    -----------------------------------
    v4.00 also has the same number of headers (3 header lines or 6 rows) as in v5.00 but the ordering is shuffled.
    
    -----------------------------------
    v3.80 has only only 2 header lines (4 rows)
    
    Note: To call a HeaderTitle item, invoke it HeaderTitle{1}{1}, since it is formatted as a cell.
    %}    
    %% 1. Opening the *.txt Data File generated by LabVIEW if none are passed
    commandwindow;
    disp('-------------------------- Running "ReadSensorDataFile.m" to read Sensor Data generated by LabVIEW data logger --------------------------')
    
    if ~exist('SensorDataFullFileName','var'), SensorDataFullFileName = []; end              % First parameter does not exist, so default it to something
    if nargin < 1 || isempty(SensorDataFullFileName)
        [SensorDataFileName, SensorDataPathName] = uigetfile({'*.txt;*.dat;*.mat', 'Data File(*.dat, *.txt, *.mat)'},'Select the Sensors Data File'); % in the future, you will need to update for *.mat files.
        SensorDataFullFileName = fullfile(SensorDataPathName, SensorDataFileName);
        fprintf('Sensor Data File opened is: \n %s \n' , SensorDataFullFileName);
        disp('----------------------------------------------------------------------------')
%     else
%         % Pass all but extension to CleanSensorDataFile
%         [SensorPath, SensorName, ~] = fileparts(SensorDataFullFileName);
    end  
    
    disp('Sensor data loading IN PROGRESS')
    SensorFileID = fopen(SensorDataFullFileName, 'r');
    disp('Sensor data loading COMPLETE.');
    disp('----------------------------------------------------------------------------')       
    
    %% 2. Initializing the variables for the Header File. One for the actual data array & the second for the corresponding titles as cells
    HeaderData = [];
    HeaderTitle = {};
    
    %% 3. Choosing the number of header lines in the versions. A default value of 5 lines based on the latest version
    prompt = ['Enter the number of lines in the header.\n    v15.00 has 8 lines,\n    v12.00-14.00 has 7 lines,\n    v10.00-11.00 has 6 lines,\n    v8.00-9.70 has 5 lines,\n    ' ...
        'v5.20-7.40 has 4 lines,\n    v4.00-5.00 has 3 lines,\n    v3.80 has 2 lines.\n    [Default = 8]: '];
    HeaderLinesCount = input(prompt);
    if isempty(HeaderLinesCount) 
        HeaderLinesCount = 8;
    end
    
    %% 4. Reading the Header of Data File. This code will read one line at a time with
    % Note: fgetl() reads lines one at a time in the line.
    % Reading each line and the subsequent line
    for ii=1:HeaderLinesCount      
        HeaderTitle{ii} = strsplit(fgetl(SensorFileID),'\t');                                  % Store the Header Titles Just In Case
        HeaderData = [HeaderData ; sscanf(fgetl(SensorFileID) , '%f\t%f\t%f\t%f\t%f\n')'];    % Appending the Header Data
    end
    disp('-------------------------- Loading sensor data header COMPLETE! --------------------------')
end

